apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agent
  labels:
    app: agent
    component: agent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: agent
      component: agent
