apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agent-headless
  labels:
    app: agent
    component: agent-headless
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: agent
      component: agent-headless
